const URLMap = {
// accounting:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/accounting/accounting-quiz.md',
// adobeacrobat:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-acrobat/adobe-acrobat-quiz.md',
// adobeillustrator:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-illustrator/adobe-illustrator-quiz.md',
// adobeindesign:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-in-design/adobe-in-design-quiz.md',
// adobelightroom:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-lightroom/adobe-lightroom-quiz.md',
// adobephotoshop:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-photoshop/adobe-photoshop-quiz.md',
// adobepremierepro:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-premiere-pro/adobe-premiere-pro-quiz.md',
// adobexd:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/adobe-xd/adobe-xd-quiz.md',
agilemethodologies:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/agile-methodologies/agile-methodologies-quiz.md',
android:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/android/android-quiz.md',
angular:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/angular/angular-quiz.md',
autocad:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/autocad/autocad-quiz.md',
autodeskfusion360:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/autodesk-fusion-360/autodesk-fusion-360-quiz.md',
awslambda:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/aws-lambda/aws-lambda-quiz.md',
aws:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/aws/aws-quiz.md',
bash:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/bash/bash-quiz.md',
csharp:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/c%23/c-sharp-quiz.md',
cplusplus:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/c%2B%2B/c%2B%2Bquiz.md',
c:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/c-(programming-language)/c-quiz.md',
css:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/css/css-quiz.md',
cybersecurity:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/cybersecurity/cybersecurity-quiz.md',
django:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/django/django-quiz.md',
dotnetframework:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/dotnet-framework/dotnet-framework-quiz.md',
eclipse:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/eclipse/eclipse-quiz.md',
frontenddevelopment:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/front-end-development/front-end-development-quiz.md',
git:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/git/git-quiz.md',
go:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/go/go-quiz.md',
googleads:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/google-ads/google-ads-quiz.md',
googleanalytics:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/google-analytics/google-analytics-quiz.md',
googlecloudplatform:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/google-cloud-platform/gcp-quiz.md',
hadoop:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/hadoop/hadoop-quiz.md',
html:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/html/html-quiz.md',
itoperations:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/it-operations/it-operations-quiz.md',
java:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/java/java-quiz.md',
javascript:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/javascript/javascript-quiz.md',
jquery:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/jquery/jquery-quiz.md',
json:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/json/json-quiz.md',
kotlin:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/kotlin/kotlin-quiz.md',
linux:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/linux/linux-assesment.md',
machinelearning:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/machine-learning/machine-learning-quiz.md',
matlab:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/matlab/matlab-quiz.md',
maven:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/maven/maven-quiz.md',
microsoftaccess:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-access/microsoft-access.md',
microsoftazure:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-azure/microsoft-azure-quiz.md',
microsoftexcel:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-excel/microsoft-excel-quiz.md',
microsoftoutlook:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-outlook/microsoft-outlook-quiz.md',
microsoftpowerbi:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-power-bi/microsoft-power-bi-quiz.md',
microsoftpowerpoint:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-power-point/microsoft-power-point-quiz.md',
microsoftproject:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-project/microsoft-project-quiz.md',
microsoftword:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/microsoft-word/microsoft-word-quiz.md',
mongodb:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/mongodb/mongodb-quiz.md',
mysql:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/mysql/mysql-quiz.md',
nodejs:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/node.js/node.js-quiz.md',
nosql:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/nosql/nosql-quiz.md',
objectivec:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/objective-c/objective-c-quiz.md',
oop:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/oop/object-oriented-programming-quiz.md',
php:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/php/php-quiz.md',
python:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/python/python-quiz.md',
quickbooks:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/quickbooks/quickbooks-quiz.md',
r:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/r/r-quiz.md',
react:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/react/reactjs-quiz.md',
restapi:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/rest-api/rest-api-quiz.md',
rubyonrails:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/ruby-on-rails/ruby-on-rails-quiz.md',
rust:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/rust/rust-quiz.md',
scala:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/scala/scala-quiz.md',
seo:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/seo/search-engine-optimization-quiz.md',
sharepoint:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/sharepoint/sharepoint-quiz.md',
solidworks:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/solidworks/solidworks-quiz.md',
springframework:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/spring-framework/spring-framework-quiz.md',
swift:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/swift/swift-quiz.md',
tsql:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/t-sql/t-sql-quiz.md',
unity:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/unity/unity-quiz.md',
vba:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/vba/vba-quiz.md',
visio:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/visio/visio-quiz.md',
windowsserver:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/windows-server/windows-server-quiz.md',
wordpress:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/wordpress/wordpress-quiz.md',
xml:'https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/master/xml/xml-quiz.md'
}

const textList = [
// 'accounting',
// 'adobe acrobat',
// 'adobe illustrator',
// 'adobe in design',
// 'adobe lightroom',
// 'adobe photoshop',
// 'adobe premiere pro',
// 'adobe xd',
'agile methodologies',
'android',
'angular',
'autocad',
'autodesk fusion 360',
'aws lambda',
'aws',
'bash',
'c#',
'c++',
'c',
'css',
'cybersecurity',
'django',
'dotnet framework',
'eclipse',
'frontend development',
'git',
'go',
'google ads',
'google analytics',
'google cloud platform',
'hadoop',
'html',
'it operations',
'java',
'javascript',
'jquery',
'json',
'kotlin',
'linux',
'machine learning',
'matlab',
'maven',
'microsoft access',
'microsoft azure',
'microsoft excel',
'microsoft outlook',
'microsoft power bi',
'microsoft power point',
'microsoft project',
'microsoft word',
'mongodb',
'mysql',
'node.js',
'nosql',
'objective c',
'oop',
'php',
'python',
'quickbooks',
'r',
'react',
'rest api',
'ruby on rails',
'rust',
'scala',
'seo',
'sharepoint',
'solidworks',
'spring framework',
'swift',
't-sql',
'unity',
'vba',
'visio',
'windows-server',
'wordpress',
'xml',
]

const convertToKeys = (text) => text.replace('-','').replace('++','plusplus').replace('#','sharp').replace('.','').replace(' ','')

export {convertToKeys, textList, URLMap}